version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "11:00"
    allow:
      - dependency-name: "@ddbeck/mdn-content-inventory"
      - dependency-name: web-features
      - dependency-name: web-specs

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@ddbeck/mdn-content-inventory"
      - dependency-name: web-features
      - dependency-name: web-specs
    groups:
      prod:
        dependency-type: production
        update-types:
          - minor
          - patch
      dev:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci(deps): "
