language: node_js
node_js: stable
sudo: false
before_install: curl -L https://unpkg.com/@pnpm/self-installer | node
install: pnpm install --frozen-lockfile
notifications:
  email: false
deploy:
  provider: npm
  email: mdn-npm@mozilla.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: mdn/browser-compat-data
