name: Add artifacts on push

on:
  push:

permissions:
  contents: read

jobs:
  test:
    name: Enumerate and diff features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # get the full repository checkout, not just the inciting commit
          persist-credentials: false
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: ".nvmrc"
          cache: npm
          package-manager-cache: true
      - run: npm ci
      - run: node ./scripts/enumerate-features.js features.json
      - run: node ./scripts/diff-features.js --no-github --format=json > features.diff.json
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: enumerate-features
          path: features.json
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: diff-features
          path: features.diff.json
