name: Add artifacts on push

on:
  push:

permissions:
  contents: read

jobs:
  test:
    name: Enumerate and diff features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # get the full repository checkout, not just the inciting commit
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - run: npm ci
      - run: npx tsx ./scripts/enumerate-features.ts features.json
      - run: npx tsx ./scripts/diff-features.ts --no-github --format=json > features.diff.json
      - uses: actions/upload-artifact@v4
        with:
          name: enumerate-features
          path: features.json
      - uses: actions/upload-artifact@v4
        with:
          name: diff-features
          path: features.diff.json
