name: Add artifacts on push

on:
  push: []

jobs:
  test:
    name: Enumerate and diff features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # get the full repository checkout, not just the inciting commit
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npx ts-node ./scripts/enumerate-features.ts features.json
      - run: npx ts-node ./scripts/diff-features.ts --no-github --format=json > features.diff.json
      - uses: actions/upload-artifact@v2
        with:
          name: enumerate-features
          path: features.json
      - uses: actions/upload-artifact@v2
        with:
          name: diff-features
          path: features.diff.json
