name: Close incomplete issue templates
on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  close-issues-if-invalid:
    runs-on: ubuntu-latest
    steps:
      - uses: queengooborg/invalid-issue-closer@v1.5.0
        id: spam-check
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: "spam"
          lock: "spam"
          comment: |
            This issue has been identified as spam and has been automatically closed and locked.
          normalize-newlines: true
          body-is-blank: true
      - uses: queengooborg/invalid-issue-closer@v1.5.0
        if: steps.spam-check.outputs.was-closed == "false"
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: "invalid"
          comment: |
            This issue was automatically closed because the title was left as the default, and a summary was not added.

            If this is not a spam issue, please replace the `<SUMMARIZE THE PROBLEM>` part of the title with a short summary of the reported issue, and then post a follow-up comment.  A maintainer will review your issue and reopen it if needed.
          normalize-newlines: true
          title-contains: "<SUMMARIZE THE PROBLEM>"
