name: Pull Request Labeler
on:
  pull_request_target:

permissions:
  contents: read # to determine modified files
  issues: write # pr-size-labeler uses the issues API until https://github.com/CodelyTV/pr-size-labeler/pull/89 is merged
  pull-requests: write # to add labels to PRs

jobs:
  label-py-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true

  label-by-size:
    if: github.secret_source == 'Actions' && !startsWith(github.event.pull_request.title, 'Release v')
    needs: label-py-path
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/pr-size-labeler@1c3422395d899286d5ee2c809fd5aed264d5eb9b # v1.10.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_api_url: "https://api.github.com"
          xs_label: "size:xs"
          xs_max_size: "6"
          s_label: "size:s"
          s_max_size: "24"
          m_label: "size:m"
          m_max_size: "100"
          l_label: "size:l"
          l_max_size: "1000"
          xl_label: "size:xl"
          fail_if_xl: "false"
          message_if_xl: ""
