name: Reviewdog

on:
  pull_request_target:
    branches: ["main"]

jobs:
  fix:
    name: Fix
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - run: npm ci

      - run: npm run fix
        env:
          FORCE_COLOR: 3

      - run: git diff > diff.patch

      - name: Upload diff
        uses: actions/upload-artifact@v4
        with:
          name: diff
          path: diff.patch

  suggest:
    name: Suggest
    needs: fix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Download diff
        uses: actions/download-artifact@v4
        with:
          name: diff

      - name: Setup
        uses: reviewdog/action-setup@3f401fe1d58fe77e10d665ab713057375e39b887 # v1.3.0
        with:
          reviewdog_version: latest

      - name: Suggest changes
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat diff.patch | reviewdog \
            -name="bcd-linter" \
            -f=diff \
            -f.diff.strip=1 \
            -filter-mode=diff_context \
            -reporter=github-pr-review
